"""Dodanie pola daty sprzedaży i numeru konta bankowego

Revision ID: 1c22d8d1ca7c
Revises: ea15ced7ed55
Create Date: 2025-03-08 00:40:11.122025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c22d8d1ca7c'
down_revision = 'ea15ced7ed55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bank_account', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_column('bank_account')

    # ### end Alembic commands ###
